In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
dt=np.array([1,2,3,4])
sr=pd.Series(dt,index=['alpha','beta','gama','delta'])
print(sr)
print(sr['delta'])


alpha    1
beta     2
gama     3
delta    4
dtype: int32
4


In [3]:
import pandas as pd  
a = pd.Series()  
print (a)  


Series([], dtype: object)


In [4]:
import pandas as pd  
import numpy as np  
sr = {'name' : 'creative', 'branch' : 'katargam', 'no' : 333}  
a = pd.Series(sr)  
print (a) 


name      creative
branch    katargam
no             333
dtype: object


In [5]:
import pandas as pd  
import numpy as np  
sr=pd.Series(4,index=[0,1,2,3])
print(sr)



0    4
1    4
2    4
3    4
dtype: int64


In [10]:
import pandas as pd
import pandas as pd
import numpy as np
dt=np.array([1,2,3,4 ,12])
sr=pd.Series(dt,index=['alpha','beta','gama','delta','Epsilon',])
print(sr)
print(sr.empty)
print(sr.hasnans)
print(len(sr))
print(sr.count)
print(sr.shape)
print(sr.nbytes)


[ 1  2  3  4 12]


In [7]:
import pandas as pd   
a=pd.Series(data=[12,34,56,67,78])   
b=pd.Series(data=[10.5,20.5,30.5], index=['a','b','c'])   
print(a.index)   
print(a.values)   
print(b.index)   
print(b.values)


RangeIndex(start=0, stop=5, step=1)
[12 34 56 67 78]
Index(['a', 'b', 'c'], dtype='object')
[10.5 20.5 30.5]


In [8]:
import pandas as pd
import numpy as np
dt=np.array([1,2,3,4])
sr=pd.Series(dt,index=['alpha','beta','gama','delta'])
print(sr)
print(sr.shape) 

alpha    1
beta     2
gama     3
delta    4
dtype: int32
(4,)


In [9]:
import numpy as np
import pandas as pd
a=pd.Series(data=[12,34,56,67,78])
b=pd.Series(data=[10.5,20.5,30.5], index=['a','b','c'])
print(b.dtype) 

float64


In [10]:
import pandas as pd

word_list = pd.Series(['CREATIVE', 'DESIGN', '&', 'MULTIMEDIA', 'INSTITUTE'])

output = []

for word in word_list:
    if word.isalpha():
        output += word[0]

print(output)


['C', 'D', 'M', 'I']


In [2]:
import pandas as pd

word_list = ['CREATIVE', 'DESIGN', '&', 'MULTIMEDIA', 'INSTITUTE']
output = []
value =input("enter a latter:").upper()

for i in range (len(word_list)):
    if value==word_list[i][0]:
        output.append(word_list[i])
print(output)

enter a latter:c
['CREATIVE']


In [12]:
word_list = ['CREATIVE', 'DESIGN', '&', 'MULTIMEDIA', 'INSTITUTE']

output = []

for word in word_list:
    output.append(len(word))

print("Count list:", output)


Count list: [8, 6, 1, 10, 9]


In [2]:
import pandas as pd


s = pd.Series([3, 1, 2, 5, 4])



transposed_series = s.T
print("transposed series\n",transposed_series)

series = s.sort_values()
print("sort series\n",series)

description = s.describe()
print("discription\n",description)

first_elements = s.head(10)
print("first element\n",first_elements)

small_elements = s.nsmallest()
print("small element\n",small_elements)

list_data = s.tolist()
print(list_data)

transposed series
 0    3
1    1
2    2
3    5
4    4
dtype: int64
sort series
 1    1
2    2
0    3
4    4
3    5
dtype: int64
discription
 count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64
first element
 0    3
1    1
2    2
3    5
4    4
dtype: int64
small element
 1    1
2    2
0    3
4    4
3    5
dtype: int64
[3, 1, 2, 5, 4]


In [5]:
a=[[12,34,56,67,78],[12,34,56,67,78]]
df=pd.DataFrame(a)
df

0   1   2   3   4
0  12  34  56  67  78
1  12  34  56  67  78

In [7]:
import pandas as pd  
df = pd.DataFrame()  
print (df)


Empty DataFrame
Columns: []
Index: []


In [9]:
import pandas as pd 
l=[10,11,12,13,14,55]

df = pd.DataFrame(l)  
print (df) 


    0
0  10
1  11
2  12
3  13
4  14
5  55


In [10]:
import pandas as pd 
l={'id':[1,2,3],'name':['haresh','shailesh','mohit']}

df = pd.DataFrame(l)  
print (df) 


   id      name
0   1    haresh
1   2  shailesh
2   3     mohit


In [11]:
import pandas as pd 

ans={'design':pd.Series([1,2,3],index=['a','b','c']),'android':pd.Series([10,11,12],index=['a','b','c'])}

rs=pd.DataFrame(ans)
print(rs)


   design  android
a       1       10
b       2       11
c       3       12


In [12]:
import pandas as pd 

ans={'design':pd.Series([1,2,3],index=['a','b','c']),'android':pd.Series([10,11,12],index=['a','b','c'])}

rs=pd.DataFrame(ans)
rs['design']


a    1
b    2
c    3
Name: design, dtype: int64

In [14]:
import pandas as pd 

ans={'design':pd.Series([1,2,3],index=['a','b','c']),'android':pd.Series([10,11,12],index=['a','b','c'])}

rs=pd.DataFrame(ans)
rs['flutter']=pd.Series([20,30,40],index=['a','b','c'])
print(rs)


   design  android  flutter
a       1       10       20
b       2       11       30
c       3       12       40


In [16]:
ans={'design':pd.Series([1,2,3],index=['a','b','c']),'android':pd.Series([10,11,12],index=['a','b','c'])}

rs=pd.DataFrame(ans)
rs['flutter']=pd.Series([20,30,40],index=['a','b','c'])

rs['python']=rs['flutter']+rs['android']
print(rs)


   design  android  flutter  python
a       1       10       20      30
b       2       11       30      41
c       3       12       40      52
